### ISSUE TITLE
Game over state bug

### ISSUE THREAD

**Issue by clothing-hanger** [HTV04/funkin-rewritten#2] opened 2021-07-22 18:35 UTC
I pressed + right as the song was restarting after the game over screen, and then there was no music, the only sounds were the miss sounds, and then I game overed again and the game over screen looks normal and the music is playing but pressing A doesn't go back to the song

**Comment by JaredYoshi** [comment] 2021-07-27 01:58
lol

**Comment by HTV04** [comment] 2021-07-30 00:44
> I pressed + right as the song was restarting after the game over screen, and then there was no music, the only sounds were the miss sounds, and then I game overed again and the game over screen looks normal and the music is playing but pressing A doesn't go back to the song

I'm preparing a fix for this, and if everything goes as planned it should be fixed by v1.0.1.

**Comment by HTV04** [comment] 2021-08-02 21:00
I tried fixing this, but the issue seems to be both hard to reproduce and hard to fix due to the way the game's timers work. It seems to be unlikely that someone would encounter this bug during normal gameplay, so I'll have to put a pin in this for now.

**Comment by HTV04** [comment] 2021-08-11 06:09
What Week were you playing on when you encountered this bug?

**Comment by HTV04** [comment] 2021-09-08 23:01
Assuming this has been resolved, so I'll close this. Please let me know if you encounter the bug again @clothing-hanger

**Closed by HTV04** 2021-09-08 23:01 UTC
Labels: bug
